<?php

namespace App\Lib;

class AutoFaker
{
    function getCar() {
        $cars = [
            ['brand' => 'Abarth', 'model' => '124'],
            ['brand' => 'Abarth', 'model' => '500'],
            ['brand' => 'Abarth', 'model' => '595'],
            ['brand' => 'Abarth', 'model' => 'Punto'],
            ['brand' => 'Aiways', 'model' => 'U5'],
            ['brand' => 'Aiways', 'model' => 'U6'],
            ['brand' => 'Alfa', 'model' => 'Romeo 145'],
            ['brand' => 'Alfa', 'model' => 'Romeo 146'],
            ['brand' => 'Alfa', 'model' => 'Romeo 147'],
            ['brand' => 'Alfa', 'model' => 'Romeo 155'],
            ['brand' => 'Alfa', 'model' => 'Romeo 156'],
            ['brand' => 'Alfa', 'model' => 'Romeo 159'],
            ['brand' => 'Alfa', 'model' => 'Romeo 164'],
            ['brand' => 'Alfa', 'model' => 'Romeo 166'],
            ['brand' => 'Alfa', 'model' => 'Romeo 33'],
            ['brand' => 'Alfa', 'model' => 'Romeo 4C'],
            ['brand' => 'Alfa', 'model' => 'Romeo 75'],
            ['brand' => 'Alfa', 'model' => 'Romeo 8C'],
            ['brand' => 'Alfa', 'model' => 'Romeo Brera'],
            ['brand' => 'Alfa', 'model' => 'Romeo Giulia'],
            ['brand' => 'Alfa', 'model' => 'Romeo Giulietta'],
            ['brand' => 'Alfa', 'model' => 'Romeo GT'],
            ['brand' => 'Alfa', 'model' => 'Romeo GTV'],
            ['brand' => 'Alfa', 'model' => 'Romeo Mito'],
            ['brand' => 'Alfa', 'model' => 'Romeo Spider'],
            ['brand' => 'Alfa', 'model' => 'Romeo Stelvio'],
            ['brand' => 'Alfa', 'model' => 'Romeo Tonale'],
            ['brand' => 'Alpine', 'model' => 'A110'],
            ['brand' => 'Aston', 'model' => 'Martin Cygnet'],
            ['brand' => 'Aston', 'model' => 'Martin DB11'],
            ['brand' => 'Aston', 'model' => 'Martin DB7'],
            ['brand' => 'Aston', 'model' => 'Martin DB9'],
            ['brand' => 'Aston', 'model' => 'Martin DBS'],
            ['brand' => 'Aston', 'model' => 'Martin DBX'],
            ['brand' => 'Aston', 'model' => 'Martin Rapide'],
            ['brand' => 'Aston', 'model' => 'Martin Vanquish'],
            ['brand' => 'Aston', 'model' => 'Martin Vantage'],
            ['brand' => 'Aston', 'model' => 'Martin Virage'],
            ['brand' => 'Audi', 'model' => '100'],
            ['brand' => 'Audi', 'model' => '80'],
            ['brand' => 'Audi', 'model' => '90'],
            ['brand' => 'Audi', 'model' => 'A1'],
            ['brand' => 'Audi', 'model' => 'A2'],
            ['brand' => 'Audi', 'model' => 'A3'],
            ['brand' => 'Audi', 'model' => 'A4'],
            ['brand' => 'Audi', 'model' => 'A5'],
            ['brand' => 'Audi', 'model' => 'A6'],
            ['brand' => 'Audi', 'model' => 'A7'],
            ['brand' => 'Audi', 'model' => 'A8'],
            ['brand' => 'Audi', 'model' => 'Cabriolet'],
            ['brand' => 'Audi', 'model' => 'Coupé'],
            ['brand' => 'Audi', 'model' => 'e-Tron'],
            ['brand' => 'Audi', 'model' => 'e-tron GT'],
            ['brand' => 'Audi', 'model' => 'Q2'],
            ['brand' => 'Audi', 'model' => 'Q3'],
            ['brand' => 'Audi', 'model' => 'Q4'],
            ['brand' => 'Audi', 'model' => 'Q5'],
            ['brand' => 'Audi', 'model' => 'Q7'],
            ['brand' => 'Audi', 'model' => 'Q8'],
            ['brand' => 'Audi', 'model' => 'Quattro'],
            ['brand' => 'Audi', 'model' => 'R8'],
            ['brand' => 'Audi', 'model' => 'TT'],
            ['brand' => 'Bentley', 'model' => 'Arnage'],
            ['brand' => 'Bentley', 'model' => 'Bentayga'],
            ['brand' => 'Bentley', 'model' => 'Continental'],
            ['brand' => 'Bentley', 'model' => 'Flying Spur'],
            ['brand' => 'Bentley', 'model' => 'Mulsanne'],
            ['brand' => 'BMW', 'model' => '1-serie'],
            ['brand' => 'BMW', 'model' => '2-serie'],
            ['brand' => 'BMW', 'model' => '2-serie Tourer'],
            ['brand' => 'BMW', 'model' => '3-serie'],
            ['brand' => 'BMW', 'model' => '3-serie GT'],
            ['brand' => 'BMW', 'model' => '4-serie'],
            ['brand' => 'BMW', 'model' => '5-serie'],
            ['brand' => 'BMW', 'model' => '5-serie GT'],
            ['brand' => 'BMW', 'model' => '6-serie'],
            ['brand' => 'BMW', 'model' => '6-serie GT'],
            ['brand' => 'BMW', 'model' => '7-serie'],
            ['brand' => 'BMW', 'model' => '8-serie'],
            ['brand' => 'BMW', 'model' => 'i3'],
            ['brand' => 'BMW', 'model' => 'i4'],
            ['brand' => 'BMW', 'model' => 'i7'],
            ['brand' => 'BMW', 'model' => 'i8'],
            ['brand' => 'BMW', 'model' => 'iX'],
            ['brand' => 'BMW', 'model' => 'X1'],
            ['brand' => 'BMW', 'model' => 'X2'],
            ['brand' => 'BMW', 'model' => 'X3'],
            ['brand' => 'BMW', 'model' => 'X4'],
            ['brand' => 'BMW', 'model' => 'X5'],
            ['brand' => 'BMW', 'model' => 'X6'],
            ['brand' => 'BMW', 'model' => 'X7'],
            ['brand' => 'BMW', 'model' => 'XM'],
            ['brand' => 'BMW', 'model' => 'Z3'],
            ['brand' => 'BMW', 'model' => 'Z4'],
            ['brand' => 'BMW', 'model' => 'Z8'],
            ['brand' => 'Bugatti', 'model' => 'Veyron'],
            ['brand' => 'BYD', 'model' => 'Atto 3'],
            ['brand' => 'BYD', 'model' => 'Han'],
            ['brand' => 'BYD', 'model' => 'Tang'],
            ['brand' => 'Cadillac', 'model' => 'ATS'],
            ['brand' => 'Cadillac', 'model' => 'BLS'],
            ['brand' => 'Cadillac', 'model' => 'CT6'],
            ['brand' => 'Cadillac', 'model' => 'CTS'],
            ['brand' => 'Cadillac', 'model' => 'Escalade'],
            ['brand' => 'Cadillac', 'model' => 'Seville'],
            ['brand' => 'Cadillac', 'model' => 'SRX'],
            ['brand' => 'Cadillac', 'model' => 'STS'],
            ['brand' => 'Cadillac', 'model' => 'XLR'],
            ['brand' => 'Cadillac', 'model' => 'XT5'],
            ['brand' => 'Chevrolet', 'model' => 'Alero'],
            ['brand' => 'Chevrolet', 'model' => 'Aveo'],
            ['brand' => 'Chevrolet', 'model' => 'Blazer'],
            ['brand' => 'Chevrolet', 'model' => 'Camaro'],
            ['brand' => 'Chevrolet', 'model' => 'Captiva'],
            ['brand' => 'Chevrolet', 'model' => 'Corvette'],
            ['brand' => 'Chevrolet', 'model' => 'Cruze'],
            ['brand' => 'Chevrolet', 'model' => 'Epica'],
            ['brand' => 'Chevrolet', 'model' => 'Evanda'],
            ['brand' => 'Chevrolet', 'model' => 'HHR'],
            ['brand' => 'Chevrolet', 'model' => 'Kalos'],
            ['brand' => 'Chevrolet', 'model' => 'Lacetti'],
            ['brand' => 'Chevrolet', 'model' => 'Matiz'],
            ['brand' => 'Chevrolet', 'model' => 'Nubira'],
            ['brand' => 'Chevrolet', 'model' => 'Orlando'],
            ['brand' => 'Chevrolet', 'model' => 'Spark'],
            ['brand' => 'Chevrolet', 'model' => 'Tacuma'],
            ['brand' => 'Chevrolet', 'model' => 'Trax'],
            ['brand' => 'Chevrolet', 'model' => 'Volt'],
            ['brand' => 'Chrysler', 'model' => '300C'],
            ['brand' => 'Chrysler', 'model' => '300M'],
            ['brand' => 'Chrysler', 'model' => 'Crossfire'],
            ['brand' => 'Chrysler', 'model' => 'Grand Voyager'],
            ['brand' => 'Chrysler', 'model' => 'Neon'],
            ['brand' => 'Chrysler', 'model' => 'New Yorker'],
            ['brand' => 'Chrysler', 'model' => 'PT Cruiser'],
            ['brand' => 'Chrysler', 'model' => 'Sebring'],
            ['brand' => 'Chrysler', 'model' => 'Stratus'],
            ['brand' => 'Chrysler', 'model' => 'Viper'],
            ['brand' => 'Chrysler', 'model' => 'Vision'],
            ['brand' => 'Chrysler', 'model' => 'Voyager'],
            ['brand' => 'Citroën', 'model' => '2CV'],
            ['brand' => 'Citroën', 'model' => 'Berlingo'],
            ['brand' => 'Citroën', 'model' => 'BX'],
            ['brand' => 'Citroën', 'model' => 'C-Crosser'],
            ['brand' => 'Citroën', 'model' => 'C-Zero'],
            ['brand' => 'Citroën', 'model' => 'C1'],
            ['brand' => 'Citroën', 'model' => 'C2'],
            ['brand' => 'Citroën', 'model' => 'C3'],
            ['brand' => 'Citroën', 'model' => 'C3 Aircross'],
            ['brand' => 'Citroën', 'model' => 'C3 Picasso'],
            ['brand' => 'Citroën', 'model' => 'C4'],
            ['brand' => 'Citroën', 'model' => 'C4 Aircross'],
            ['brand' => 'Citroën', 'model' => 'C4 Cactus'],
            ['brand' => 'Citroën', 'model' => 'C4 Picasso'],
            ['brand' => 'Citroën', 'model' => 'C4 SpaceTourer'],
            ['brand' => 'Citroën', 'model' => 'C5'],
            ['brand' => 'Citroën', 'model' => 'C5 Aircross'],
            ['brand' => 'Citroën', 'model' => 'C5 X'],
            ['brand' => 'Citroën', 'model' => 'C6'],
            ['brand' => 'Citroën', 'model' => 'C8'],
            ['brand' => 'Citroën', 'model' => 'CX'],
            ['brand' => 'Citroën', 'model' => 'DS3'],
            ['brand' => 'Citroën', 'model' => 'DS4'],
            ['brand' => 'Citroën', 'model' => 'DS5'],
            ['brand' => 'Citroën', 'model' => 'Evasion'],
            ['brand' => 'Citroën', 'model' => 'Jumper'],
            ['brand' => 'Citroën', 'model' => 'Jumpy'],
            ['brand' => 'Citroën', 'model' => 'Nemo'],
            ['brand' => 'Citroën', 'model' => 'Saxo'],
            ['brand' => 'Citroën', 'model' => 'Xantia'],
            ['brand' => 'Citroën', 'model' => 'XM'],
            ['brand' => 'Citroën', 'model' => 'Xsara'],
            ['brand' => 'Citroën', 'model' => 'Xsara Picasso'],
            ['brand' => 'Citroën', 'model' => 'ZX'],
            ['brand' => 'Cupra', 'model' => 'Born'],
            ['brand' => 'Cupra', 'model' => 'Formentor'],
            ['brand' => 'Cupra', 'model' => 'Leon'],
            ['brand' => 'Dacia', 'model' => 'Dokker'],
            ['brand' => 'Dacia', 'model' => 'Duster'],
            ['brand' => 'Dacia', 'model' => 'Jogger'],
            ['brand' => 'Dacia', 'model' => 'Lodgy'],
            ['brand' => 'Dacia', 'model' => 'Logan'],
            ['brand' => 'Dacia', 'model' => 'Sandero'],
            ['brand' => 'Dacia', 'model' => 'Spring'],
            ['brand' => 'Daewoo', 'model' => 'Espero'],
            ['brand' => 'Daewoo', 'model' => 'Evanda'],
            ['brand' => 'Daewoo', 'model' => 'Kalos'],
            ['brand' => 'Daewoo', 'model' => 'Lacetti'],
            ['brand' => 'Daewoo', 'model' => 'Lanos'],
            ['brand' => 'Daewoo', 'model' => 'Leganza'],
            ['brand' => 'Daewoo', 'model' => 'Matiz'],
            ['brand' => 'Daewoo', 'model' => 'Nexia'],
            ['brand' => 'Daewoo', 'model' => 'Nubira'],
            ['brand' => 'Daewoo', 'model' => 'Tacuma'],
            ['brand' => 'Daihatsu', 'model' => 'Applause'],
            ['brand' => 'Daihatsu', 'model' => 'Charade'],
            ['brand' => 'Daihatsu', 'model' => 'Copen'],
            ['brand' => 'Daihatsu', 'model' => 'Cuore'],
            ['brand' => 'Daihatsu', 'model' => 'Feroza'],
            ['brand' => 'Daihatsu', 'model' => 'Materia'],
            ['brand' => 'Daihatsu', 'model' => 'Move'],
            ['brand' => 'Daihatsu', 'model' => 'Rocky'],
            ['brand' => 'Daihatsu', 'model' => 'Sirion'],
            ['brand' => 'Daihatsu', 'model' => 'Terios'],
            ['brand' => 'Daihatsu', 'model' => 'Trevis'],
            ['brand' => 'Daihatsu', 'model' => 'Valéra'],
            ['brand' => 'Daihatsu', 'model' => 'Young RV'],
            ['brand' => 'Dodge', 'model' => 'Avenger'],
            ['brand' => 'Dodge', 'model' => 'Caliber'],
            ['brand' => 'Dodge', 'model' => 'Journey'],
            ['brand' => 'Dodge', 'model' => 'Nitro'],
            ['brand' => 'Dodge', 'model' => 'Viper'],
            ['brand' => 'Donkervoort', 'model' => 'D8'],
            ['brand' => 'Donkervoort', 'model' => 'D8 GTO'],
            ['brand' => 'DS', 'model' => '3'],
            ['brand' => 'DS', 'model' => '3 Crossback'],
            ['brand' => 'DS', 'model' => '4'],
            ['brand' => 'DS', 'model' => '5'],
            ['brand' => 'DS', 'model' => '7'],
            ['brand' => 'DS', 'model' => '9'],
            ['brand' => 'Ferrari', 'model' => '296'],
            ['brand' => 'Ferrari', 'model' => '348'],
            ['brand' => 'Ferrari', 'model' => '360'],
            ['brand' => 'Ferrari', 'model' => '456'],
            ['brand' => 'Ferrari', 'model' => '458'],
            ['brand' => 'Ferrari', 'model' => '488'],
            ['brand' => 'Ferrari', 'model' => '550'],
            ['brand' => 'Ferrari', 'model' => '575M'],
            ['brand' => 'Ferrari', 'model' => '599'],
            ['brand' => 'Ferrari', 'model' => '612'],
            ['brand' => 'Ferrari', 'model' => '812'],
            ['brand' => 'Ferrari', 'model' => 'California'],
            ['brand' => 'Ferrari', 'model' => 'Enzo'],
            ['brand' => 'Ferrari', 'model' => 'F12'],
            ['brand' => 'Ferrari', 'model' => 'F355'],
            ['brand' => 'Ferrari', 'model' => 'F430'],
            ['brand' => 'Ferrari', 'model' => 'F8'],
            ['brand' => 'Ferrari', 'model' => 'FF'],
            ['brand' => 'Ferrari', 'model' => 'GTC4'],
            ['brand' => 'Ferrari', 'model' => 'LaFerrari'],
            ['brand' => 'Ferrari', 'model' => 'Portofino'],
            ['brand' => 'Ferrari', 'model' => 'Roma'],
            ['brand' => 'Ferrari', 'model' => 'SF90'],
            ['brand' => 'Fiat', 'model' => '124'],
            ['brand' => 'Fiat', 'model' => '500'],
            ['brand' => 'Fiat', 'model' => '500L'],
            ['brand' => 'Fiat', 'model' => '500X'],
            ['brand' => 'Fiat', 'model' => '600'],
            ['brand' => 'Fiat', 'model' => 'Barchetta'],
            ['brand' => 'Fiat', 'model' => 'Brava'],
            ['brand' => 'Fiat', 'model' => 'Bravo'],
            ['brand' => 'Fiat', 'model' => 'Cinquecento'],
            ['brand' => 'Fiat', 'model' => 'Coupé'],
            ['brand' => 'Fiat', 'model' => 'Croma'],
            ['brand' => 'Fiat', 'model' => 'Doblò'],
            ['brand' => 'Fiat', 'model' => 'Ducato'],
            ['brand' => 'Fiat', 'model' => 'Fiorino'],
            ['brand' => 'Fiat', 'model' => 'Fullback'],
            ['brand' => 'Fiat', 'model' => 'Idea'],
            ['brand' => 'Fiat', 'model' => 'Marea'],
            ['brand' => 'Fiat', 'model' => 'Multipla'],
            ['brand' => 'Fiat', 'model' => 'Palio'],
            ['brand' => 'Fiat', 'model' => 'Panda'],
            ['brand' => 'Fiat', 'model' => 'Punto'],
            ['brand' => 'Fiat', 'model' => 'Qubo'],
            ['brand' => 'Fiat', 'model' => 'Scudo'],
            ['brand' => 'Fiat', 'model' => 'Sedici'],
            ['brand' => 'Fiat', 'model' => 'Seicento'],
            ['brand' => 'Fiat', 'model' => 'Stilo'],
            ['brand' => 'Fiat', 'model' => 'Strada'],
            ['brand' => 'Fiat', 'model' => 'Talento'],
            ['brand' => 'Fiat', 'model' => 'Tipo'],
            ['brand' => 'Fiat', 'model' => 'Ulysse'],
            ['brand' => 'Fiat', 'model' => 'Uno'],
            ['brand' => 'Fisker', 'model' => 'Karma'],
            ['brand' => 'Fisker', 'model' => 'Ocean'],
            ['brand' => 'Ford', 'model' => 'B-MAX'],
            ['brand' => 'Ford', 'model' => 'C-MAX'],
            ['brand' => 'Ford', 'model' => 'Ecosport'],
            ['brand' => 'Ford', 'model' => 'Edge'],
            ['brand' => 'Ford', 'model' => 'Escort'],
            ['brand' => 'Ford', 'model' => 'Explorer'],
            ['brand' => 'Ford', 'model' => 'Fiesta'],
            ['brand' => 'Ford', 'model' => 'Focus'],
            ['brand' => 'Ford', 'model' => 'Focus C-Max'],
            ['brand' => 'Ford', 'model' => 'Fusion'],
            ['brand' => 'Ford', 'model' => 'Galaxy'],
            ['brand' => 'Ford', 'model' => 'Ka'],
            ['brand' => 'Ford', 'model' => 'Ka+'],
            ['brand' => 'Ford', 'model' => 'Ka+'],
            ['brand' => 'Ford', 'model' => 'Kuga'],
            ['brand' => 'Ford', 'model' => 'Mondeo'],
            ['brand' => 'Ford', 'model' => 'Mustang'],
            ['brand' => 'Ford', 'model' => 'Mustang Mach-E'],
            ['brand' => 'Ford', 'model' => 'Puma'],
            ['brand' => 'Ford', 'model' => 'Ranger'],
            ['brand' => 'Ford', 'model' => 'S-MAX'],
            ['brand' => 'Ford', 'model' => 'Scorpio'],
            ['brand' => 'Ford', 'model' => 'Sierra'],
            ['brand' => 'Ford', 'model' => 'Tourneo Connect'],
            ['brand' => 'Ford', 'model' => 'Tourneo Courier'],
            ['brand' => 'Ford', 'model' => 'Tourneo Custom'],
            ['brand' => 'Ford', 'model' => 'Transit Connect'],
            ['brand' => 'Ford', 'model' => 'Transit Courier'],
            ['brand' => 'Ford', 'model' => 'Transit Custom'],
            ['brand' => 'Honda', 'model' => 'Accord'],
            ['brand' => 'Honda', 'model' => 'Civic'],
            ['brand' => 'Honda', 'model' => 'CR-V'],
            ['brand' => 'Honda', 'model' => 'CR-Z'],
            ['brand' => 'Honda', 'model' => 'e'],
            ['brand' => 'Honda', 'model' => 'FR-V'],
            ['brand' => 'Honda', 'model' => 'HR-V'],
            ['brand' => 'Honda', 'model' => 'Insight'],
            ['brand' => 'Honda', 'model' => 'Jazz'],
            ['brand' => 'Honda', 'model' => 'Legend'],
            ['brand' => 'Honda', 'model' => 'Logo'],
            ['brand' => 'Honda', 'model' => 'NSX'],
            ['brand' => 'Honda', 'model' => 'S2000'],
            ['brand' => 'Honda', 'model' => 'Stream'],
            ['brand' => 'Hongqi', 'model' => 'E-HS9'],
            ['brand' => 'Hummer', 'model' => 'H2'],
            ['brand' => 'Hummer', 'model' => 'H3'],
            ['brand' => 'Hyundai', 'model' => 'Accent'],
            ['brand' => 'Hyundai', 'model' => 'Atos'],
            ['brand' => 'Hyundai', 'model' => 'Bayon'],
            ['brand' => 'Hyundai', 'model' => 'Coupé'],
            ['brand' => 'Hyundai', 'model' => 'Elantra'],
            ['brand' => 'Hyundai', 'model' => 'Genesis'],
            ['brand' => 'Hyundai', 'model' => 'Getz'],
            ['brand' => 'Hyundai', 'model' => 'Grandeur'],
            ['brand' => 'Hyundai', 'model' => 'H300'],
            ['brand' => 'Hyundai', 'model' => 'i10'],
            ['brand' => 'Hyundai', 'model' => 'i20'],
            ['brand' => 'Hyundai', 'model' => 'i30'],
            ['brand' => 'Hyundai', 'model' => 'i40'],
            ['brand' => 'Hyundai', 'model' => 'Ioniq'],
            ['brand' => 'Hyundai', 'model' => 'Ioniq 5'],
            ['brand' => 'Hyundai', 'model' => 'Ioniq 6'],
            ['brand' => 'Hyundai', 'model' => 'ix20'],
            ['brand' => 'Hyundai', 'model' => 'ix35'],
            ['brand' => 'Hyundai', 'model' => 'Kona'],
            ['brand' => 'Hyundai', 'model' => 'Matrix'],
            ['brand' => 'Hyundai', 'model' => 'Nexo'],
            ['brand' => 'Hyundai', 'model' => 'Santa Fe'],
            ['brand' => 'Hyundai', 'model' => 'Scoupé'],
            ['brand' => 'Hyundai', 'model' => 'Sonata'],
            ['brand' => 'Hyundai', 'model' => 'Terracan'],
            ['brand' => 'Hyundai', 'model' => 'Trajet'],
            ['brand' => 'Hyundai', 'model' => 'Tucson'],
            ['brand' => 'Hyundai', 'model' => 'Veloster'],
            ['brand' => 'Hyundai', 'model' => 'XG'],
            ['brand' => 'Infiniti', 'model' => 'EX'],
            ['brand' => 'Infiniti', 'model' => 'FX'],
            ['brand' => 'Infiniti', 'model' => 'G'],
            ['brand' => 'Infiniti', 'model' => 'M'],
            ['brand' => 'Infiniti', 'model' => 'Q30'],
            ['brand' => 'Infiniti', 'model' => 'Q50'],
            ['brand' => 'Infiniti', 'model' => 'Q60'],
            ['brand' => 'Infiniti', 'model' => 'Q70'],
            ['brand' => 'Infiniti', 'model' => 'QX30'],
            ['brand' => 'Infiniti', 'model' => 'QX50'],
            ['brand' => 'Infiniti', 'model' => 'QX70'],
            ['brand' => 'JAC', 'model' => 'iEV7S'],
            ['brand' => 'Jaguar', 'model' => 'E-Pace'],
            ['brand' => 'Jaguar', 'model' => 'F-Pace'],
            ['brand' => 'Jaguar', 'model' => 'F-type'],
            ['brand' => 'Jaguar', 'model' => 'I-Pace'],
            ['brand' => 'Jaguar', 'model' => 'S-type'],
            ['brand' => 'Jaguar', 'model' => 'X-type'],
            ['brand' => 'Jaguar', 'model' => 'XE'],
            ['brand' => 'Jaguar', 'model' => 'XF'],
            ['brand' => 'Jaguar', 'model' => 'XJ'],
            ['brand' => 'Jaguar', 'model' => 'XJS'],
            ['brand' => 'Jaguar', 'model' => 'XK'],
            ['brand' => 'Jeep', 'model' => 'Avenger'],
            ['brand' => 'Jeep', 'model' => 'Cherokee'],
            ['brand' => 'Jeep', 'model' => 'Commander'],
            ['brand' => 'Jeep', 'model' => 'Compass'],
            ['brand' => 'Jeep', 'model' => 'Grand Cherokee'],
            ['brand' => 'Jeep', 'model' => 'Patriot'],
            ['brand' => 'Jeep', 'model' => 'Renegade'],
            ['brand' => 'Jeep', 'model' => 'Wrangler'],
            ['brand' => 'Kia', 'model' => 'Carens'],
            ['brand' => 'Kia', 'model' => 'Carnival'],
            ['brand' => 'Kia', 'model' => 'Ceed'],
            ['brand' => 'Kia', 'model' => 'Cerato'],
            ['brand' => 'Kia', 'model' => 'EV6'],
            ['brand' => 'Kia', 'model' => 'Joice'],
            ['brand' => 'Kia', 'model' => 'Magentis'],
            ['brand' => 'Kia', 'model' => 'Mentor'],
            ['brand' => 'Kia', 'model' => 'Niro'],
            ['brand' => 'Kia', 'model' => 'Opirus'],
            ['brand' => 'Kia', 'model' => 'Optima'],
            ['brand' => 'Kia', 'model' => 'Picanto'],
            ['brand' => 'Kia', 'model' => 'Pride'],
            ['brand' => 'Kia', 'model' => 'ProCeed'],
            ['brand' => 'Kia', 'model' => 'Rio'],
            ['brand' => 'Kia', 'model' => 'Sephia'],
            ['brand' => 'Kia', 'model' => 'Shuma'],
            ['brand' => 'Kia', 'model' => 'Sorento'],
            ['brand' => 'Kia', 'model' => 'Soul'],
            ['brand' => 'Kia', 'model' => 'Sportage'],
            ['brand' => 'Kia', 'model' => 'Stinger'],
            ['brand' => 'Kia', 'model' => 'Stonic'],
            ['brand' => 'Kia', 'model' => 'Venga'],
            ['brand' => 'Kia', 'model' => 'XCeed'],
            ['brand' => 'Lada', 'model' => '110'],
            ['brand' => 'Lada', 'model' => '111'],
            ['brand' => 'Lada', 'model' => '112'],
            ['brand' => 'Lada', 'model' => '2100-serie'],
            ['brand' => 'Lada', 'model' => 'Kalina'],
            ['brand' => 'Lada', 'model' => 'Niva'],
            ['brand' => 'Lada', 'model' => 'Priora'],
            ['brand' => 'Lada', 'model' => 'Samara'],
            ['brand' => 'Lamborghini', 'model' => 'Aventador'],
            ['brand' => 'Lamborghini', 'model' => 'Countach'],
            ['brand' => 'Lamborghini', 'model' => 'Diablo'],
            ['brand' => 'Lamborghini', 'model' => 'Gallardo'],
            ['brand' => 'Lamborghini', 'model' => 'Huracán'],
            ['brand' => 'Lamborghini', 'model' => 'Murciélago'],
            ['brand' => 'Lamborghini', 'model' => 'Urus'],
            ['brand' => 'Lancia', 'model' => 'Delta'],
            ['brand' => 'Lancia', 'model' => 'Flavia'],
            ['brand' => 'Lancia', 'model' => 'Kappa'],
            ['brand' => 'Lancia', 'model' => 'Lybra'],
            ['brand' => 'Lancia', 'model' => 'Musa'],
            ['brand' => 'Lancia', 'model' => 'Phedra'],
            ['brand' => 'Lancia', 'model' => 'Thema'],
            ['brand' => 'Lancia', 'model' => 'Thesis'],
            ['brand' => 'Lancia', 'model' => 'Voyager'],
            ['brand' => 'Lancia', 'model' => 'Ypsilon'],
            ['brand' => 'Land', 'model' => 'Rover Defender'],
            ['brand' => 'Land', 'model' => 'Rover Discovery'],
            ['brand' => 'Land', 'model' => 'Rover Discovery Sport'],
            ['brand' => 'Land', 'model' => 'Rover Freelander'],
            ['brand' => 'Land', 'model' => 'Rover Range Rover'],
            ['brand' => 'Land', 'model' => 'Rover Range Rover Evoque'],
            ['brand' => 'Land', 'model' => 'Rover Range Rover Sport'],
            ['brand' => 'Land', 'model' => 'Rover Range Rover Velar'],
            ['brand' => 'Lexus', 'model' => 'CT'],
            ['brand' => 'Lexus', 'model' => 'ES'],
            ['brand' => 'Lexus', 'model' => 'GS'],
            ['brand' => 'Lexus', 'model' => 'IS'],
            ['brand' => 'Lexus', 'model' => 'LC'],
            ['brand' => 'Lexus', 'model' => 'LS'],
            ['brand' => 'Lexus', 'model' => 'NX'],
            ['brand' => 'Lexus', 'model' => 'RC'],
            ['brand' => 'Lexus', 'model' => 'RX'],
            ['brand' => 'Lexus', 'model' => 'RZ'],
            ['brand' => 'Lexus', 'model' => 'SC'],
            ['brand' => 'Lexus', 'model' => 'UX'],
            ['brand' => 'Lotus', 'model' => 'Eletre'],
            ['brand' => 'Lotus', 'model' => 'Elise'],
            ['brand' => 'Lotus', 'model' => 'Emira'],
            ['brand' => 'Lotus', 'model' => 'Esprit'],
            ['brand' => 'Lotus', 'model' => 'Europa'],
            ['brand' => 'Lotus', 'model' => 'Evora'],
            ['brand' => 'Lotus', 'model' => 'Exige'],
            ['brand' => 'Lucid', 'model' => 'Air'],
            ['brand' => 'Maserati', 'model' => '3200 GT'],
            ['brand' => 'Maserati', 'model' => 'Coupé'],
            ['brand' => 'Maserati', 'model' => 'Ghibli'],
            ['brand' => 'Maserati', 'model' => 'GranCabrio'],
            ['brand' => 'Maserati', 'model' => 'GranSport'],
            ['brand' => 'Maserati', 'model' => 'GranTurismo'],
            ['brand' => 'Maserati', 'model' => 'Grecale'],
            ['brand' => 'Maserati', 'model' => 'Levante'],
            ['brand' => 'Maserati', 'model' => 'Quattroporte'],
            ['brand' => 'Maserati', 'model' => 'Spyder'],
            ['brand' => 'Maybach', 'model' => '57'],
            ['brand' => 'Maybach', 'model' => '62'],
            ['brand' => 'Mazda', 'model' => '121'],
            ['brand' => 'Mazda', 'model' => '2'],
            ['brand' => 'Mazda', 'model' => '3'],
            ['brand' => 'Mazda', 'model' => '323'],
            ['brand' => 'Mazda', 'model' => '5'],
            ['brand' => 'Mazda', 'model' => '6'],
            ['brand' => 'Mazda', 'model' => '626'],
            ['brand' => 'Mazda', 'model' => 'CX-3'],
            ['brand' => 'Mazda', 'model' => 'CX-30'],
            ['brand' => 'Mazda', 'model' => 'CX-5'],
            ['brand' => 'Mazda', 'model' => 'CX-60'],
            ['brand' => 'Mazda', 'model' => 'CX-7'],
            ['brand' => 'Mazda', 'model' => 'CX-9'],
            ['brand' => 'Mazda', 'model' => 'Demio'],
            ['brand' => 'Mazda', 'model' => 'MPV'],
            ['brand' => 'Mazda', 'model' => 'MX-3'],
            ['brand' => 'Mazda', 'model' => 'MX-30'],
            ['brand' => 'Mazda', 'model' => 'MX-5'],
            ['brand' => 'Mazda', 'model' => 'Premacy'],
            ['brand' => 'Mazda', 'model' => 'RX-8'],
            ['brand' => 'Mazda', 'model' => 'Tribute'],
            ['brand' => 'Mazda', 'model' => 'Xedos 6'],
            ['brand' => 'Mazda', 'model' => 'Xedos 9'],
            ['brand' => 'McLaren', 'model' => '12C'],
            ['brand' => 'McLaren', 'model' => '540C'],
            ['brand' => 'McLaren', 'model' => '570GT'],
            ['brand' => 'McLaren', 'model' => '570S'],
            ['brand' => 'McLaren', 'model' => '600LT'],
            ['brand' => 'McLaren', 'model' => '650S'],
            ['brand' => 'McLaren', 'model' => '675LT'],
            ['brand' => 'McLaren', 'model' => '720S'],
            ['brand' => 'McLaren', 'model' => 'Artura'],
            ['brand' => 'McLaren', 'model' => 'GT'],
            ['brand' => 'Mercedes-Benz', 'model' => '190-serie'],
            ['brand' => 'Mercedes-Benz', 'model' => '200-serie'],
            ['brand' => 'Mercedes-Benz', 'model' => 'A-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'AMG GT'],
            ['brand' => 'Mercedes-Benz', 'model' => 'AMG GT 4-Door'],
            ['brand' => 'Mercedes-Benz', 'model' => 'B-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'C-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'Citan'],
            ['brand' => 'Mercedes-Benz', 'model' => 'CL'],
            ['brand' => 'Mercedes-Benz', 'model' => 'CLA'],
            ['brand' => 'Mercedes-Benz', 'model' => 'CLC'],
            ['brand' => 'Mercedes-Benz', 'model' => 'CLK'],
            ['brand' => 'Mercedes-Benz', 'model' => 'CLS'],
            ['brand' => 'Mercedes-Benz', 'model' => 'E-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQA'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQB'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQC'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQE'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQS'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQS SUV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'G-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GL'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLA'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLB'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLC'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLE'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLK'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLS'],
            ['brand' => 'Mercedes-Benz', 'model' => 'M-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'R-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'S-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'SL'],
            ['brand' => 'Mercedes-Benz', 'model' => 'SLC'],
            ['brand' => 'Mercedes-Benz', 'model' => 'SLK'],
            ['brand' => 'Mercedes-Benz', 'model' => 'SLR McLaren'],
            ['brand' => 'Mercedes-Benz', 'model' => 'SLS AMG'],
            ['brand' => 'Mercedes-Benz', 'model' => 'Sprinter'],
            ['brand' => 'Mercedes-Benz', 'model' => 'V-klasse'],
            ['brand' => 'Mercedes-Benz', 'model' => 'Vaneo'],
            ['brand' => 'Mercedes-Benz', 'model' => 'Viano'],
            ['brand' => 'Mercedes-Benz', 'model' => 'Vito'],
            ['brand' => 'Mercedes-Benz', 'model' => 'X-klasse'],
            ['brand' => 'MG', 'model' => '4'],
            ['brand' => 'MG', 'model' => '5'],
            ['brand' => 'MG', 'model' => 'EHS'],
            ['brand' => 'MG', 'model' => 'F'],
            ['brand' => 'MG', 'model' => 'Marvel R'],
            ['brand' => 'MG', 'model' => 'TF'],
            ['brand' => 'MG', 'model' => 'ZR'],
            ['brand' => 'MG', 'model' => 'ZS'],
            ['brand' => 'MG', 'model' => 'ZT'],
            ['brand' => 'MINI', 'model' => '1000'],
            ['brand' => 'Mini', 'model' => 'Aceman'],
            ['brand' => 'MINI', 'model' => 'Cabrio'],
            ['brand' => 'MINI', 'model' => 'Clubman'],
            ['brand' => 'MINI', 'model' => 'Countryman'],
            ['brand' => 'MINI', 'model' => 'Coupé'],
            ['brand' => 'MINI', 'model' => 'Mini'],
            ['brand' => 'MINI', 'model' => 'Paceman'],
            ['brand' => 'MINI', 'model' => 'Roadster'],
            ['brand' => 'Mitsubishi', 'model' => 'ASX'],
            ['brand' => 'Mitsubishi', 'model' => 'Carisma'],
            ['brand' => 'Mitsubishi', 'model' => 'Colt'],
            ['brand' => 'Mitsubishi', 'model' => 'Eclipse Cross'],
            ['brand' => 'Mitsubishi', 'model' => 'Galant'],
            ['brand' => 'Mitsubishi', 'model' => 'Grandis'],
            ['brand' => 'Mitsubishi', 'model' => 'i-MiEV'],
            ['brand' => 'Mitsubishi', 'model' => 'L200'],
            ['brand' => 'Mitsubishi', 'model' => 'Lancer'],
            ['brand' => 'Mitsubishi', 'model' => 'Outlander'],
            ['brand' => 'Mitsubishi', 'model' => 'Outlander Sport'],
            ['brand' => 'Mitsubishi', 'model' => 'Pajero'],
            ['brand' => 'Mitsubishi', 'model' => 'Pajero Pinin'],
            ['brand' => 'Mitsubishi', 'model' => 'Pajero Sport'],
            ['brand' => 'Mitsubishi', 'model' => 'Space Star'],
            ['brand' => 'Mitsubishi', 'model' => 'Space Wagon'],
            ['brand' => 'Morgan', 'model' => '3 Wheeler'],
            ['brand' => 'Morgan', 'model' => '4/4'],
            ['brand' => 'Morgan', 'model' => 'Aero'],
            ['brand' => 'Morgan', 'model' => 'Plus 4'],
            ['brand' => 'Morgan', 'model' => 'Plus 6'],
            ['brand' => 'Morgan', 'model' => 'Plus 8'],
            ['brand' => 'Morgan', 'model' => 'Roadster'],
            ['brand' => 'Nio', 'model' => 'EL7'],
            ['brand' => 'Nio', 'model' => 'ET5'],
            ['brand' => 'Nio', 'model' => 'ET7'],
            ['brand' => 'Nissan', 'model' => '100 NX'],
            ['brand' => 'Nissan', 'model' => '300 ZX'],
            ['brand' => 'Nissan', 'model' => '350Z'],
            ['brand' => 'Nissan', 'model' => '370Z'],
            ['brand' => 'Nissan', 'model' => 'Almera'],
            ['brand' => 'Nissan', 'model' => 'Almera Tino'],
            ['brand' => 'Nissan', 'model' => 'Ariya'],
            ['brand' => 'Nissan', 'model' => 'Cube'],
            ['brand' => 'Nissan', 'model' => 'Evalia'],
            ['brand' => 'Nissan', 'model' => 'GT-R'],
            ['brand' => 'Nissan', 'model' => 'Juke'],
            ['brand' => 'Nissan', 'model' => 'Leaf'],
            ['brand' => 'Nissan', 'model' => 'Micra'],
            ['brand' => 'Nissan', 'model' => 'Murano'],
            ['brand' => 'Nissan', 'model' => 'Note'],
            ['brand' => 'Nissan', 'model' => 'NV200'],
            ['brand' => 'Nissan', 'model' => 'NV300'],
            ['brand' => 'Nissan', 'model' => 'NV400'],
            ['brand' => 'Nissan', 'model' => 'Pathfinder'],
            ['brand' => 'Nissan', 'model' => 'Patrol'],
            ['brand' => 'Nissan', 'model' => 'Pixo'],
            ['brand' => 'Nissan', 'model' => 'Primastar'],
            ['brand' => 'Nissan', 'model' => 'Primera'],
            ['brand' => 'Nissan', 'model' => 'Pulsar'],
            ['brand' => 'Nissan', 'model' => 'Qashqai'],
            ['brand' => 'Nissan', 'model' => 'Terrano'],
            ['brand' => 'Nissan', 'model' => 'X-Trail'],
            ['brand' => 'Opel', 'model' => 'Adam'],
            ['brand' => 'Opel', 'model' => 'Agila'],
            ['brand' => 'Opel', 'model' => 'Ampera'],
            ['brand' => 'Opel', 'model' => 'Ampera-e'],
            ['brand' => 'Opel', 'model' => 'Antara'],
            ['brand' => 'Opel', 'model' => 'Ascona'],
            ['brand' => 'Opel', 'model' => 'Astra'],
            ['brand' => 'Opel', 'model' => 'Calibra'],
            ['brand' => 'Opel', 'model' => 'Cascada'],
            ['brand' => 'Opel', 'model' => 'Combo'],
            ['brand' => 'Opel', 'model' => 'Corsa'],
            ['brand' => 'Opel', 'model' => 'Crossland'],
            ['brand' => 'Opel', 'model' => 'Frontera'],
            ['brand' => 'Opel', 'model' => 'Grandland'],
            ['brand' => 'Opel', 'model' => 'GT'],
            ['brand' => 'Opel', 'model' => 'Insignia'],
            ['brand' => 'Opel', 'model' => 'Kadett'],
            ['brand' => 'Opel', 'model' => 'Karl'],
            ['brand' => 'Opel', 'model' => 'Manta'],
            ['brand' => 'Opel', 'model' => 'Meriva'],
            ['brand' => 'Opel', 'model' => 'Mokka'],
            ['brand' => 'Opel', 'model' => 'Monza'],
            ['brand' => 'Opel', 'model' => 'Movano'],
            ['brand' => 'Opel', 'model' => 'Omega'],
            ['brand' => 'Opel', 'model' => 'Rekord'],
            ['brand' => 'Opel', 'model' => 'Senator'],
            ['brand' => 'Opel', 'model' => 'Signum'],
            ['brand' => 'Opel', 'model' => 'Speedster'],
            ['brand' => 'Opel', 'model' => 'Tigra'],
            ['brand' => 'Opel', 'model' => 'Tour'],
            ['brand' => 'Opel', 'model' => 'Vectra'],
            ['brand' => 'Opel', 'model' => 'Vivaro'],
            ['brand' => 'Opel', 'model' => 'Zafira'],
            ['brand' => 'Peugeot', 'model' => '1007'],
            ['brand' => 'Peugeot', 'model' => '106'],
            ['brand' => 'Peugeot', 'model' => '107'],
            ['brand' => 'Peugeot', 'model' => '108'],
            ['brand' => 'Peugeot', 'model' => '2008'],
            ['brand' => 'Peugeot', 'model' => '205'],
            ['brand' => 'Peugeot', 'model' => '206'],
            ['brand' => 'Peugeot', 'model' => '207'],
            ['brand' => 'Peugeot', 'model' => '208'],
            ['brand' => 'Peugeot', 'model' => '3008'],
            ['brand' => 'Peugeot', 'model' => '306'],
            ['brand' => 'Peugeot', 'model' => '307'],
            ['brand' => 'Peugeot', 'model' => '308'],
            ['brand' => 'Peugeot', 'model' => '309'],
            ['brand' => 'Peugeot', 'model' => '4007'],
            ['brand' => 'Peugeot', 'model' => '405'],
            ['brand' => 'Peugeot', 'model' => '406'],
            ['brand' => 'Peugeot', 'model' => '407'],
            ['brand' => 'Peugeot', 'model' => '408'],
            ['brand' => 'Peugeot', 'model' => '5008'],
            ['brand' => 'Peugeot', 'model' => '504'],
            ['brand' => 'Peugeot', 'model' => '505'],
            ['brand' => 'Peugeot', 'model' => '508'],
            ['brand' => 'Peugeot', 'model' => '605'],
            ['brand' => 'Peugeot', 'model' => '607'],
            ['brand' => 'Peugeot', 'model' => '806'],
            ['brand' => 'Peugeot', 'model' => '807'],
            ['brand' => 'Peugeot', 'model' => 'Bipper'],
            ['brand' => 'Peugeot', 'model' => 'Expert'],
            ['brand' => 'Peugeot', 'model' => 'Ion'],
            ['brand' => 'Peugeot', 'model' => 'Partner'],
            ['brand' => 'Peugeot', 'model' => 'RCZ'],
            ['brand' => 'Peugeot', 'model' => 'Rifter'],
            ['brand' => 'Peugeot', 'model' => 'Traveller'],
            ['brand' => 'Polestar', 'model' => '1'],
            ['brand' => 'Polestar', 'model' => '2'],
            ['brand' => 'Polestar', 'model' => '3'],
            ['brand' => 'Porsche', 'model' => '718'],
            ['brand' => 'Porsche', 'model' => '911'],
            ['brand' => 'Porsche', 'model' => '918'],
            ['brand' => 'Porsche', 'model' => '924'],
            ['brand' => 'Porsche', 'model' => '928'],
            ['brand' => 'Porsche', 'model' => '944'],
            ['brand' => 'Porsche', 'model' => '968'],
            ['brand' => 'Porsche', 'model' => 'Boxster'],
            ['brand' => 'Porsche', 'model' => 'Cayenne'],
            ['brand' => 'Porsche', 'model' => 'Cayman'],
            ['brand' => 'Porsche', 'model' => 'Macan'],
            ['brand' => 'Porsche', 'model' => 'Panamera'],
            ['brand' => 'Porsche', 'model' => 'Taycan'],
            ['brand' => 'Renault', 'model' => '4'],
            ['brand' => 'Renault', 'model' => '5'],
            ['brand' => 'Renault', 'model' => 'Arkana'],
            ['brand' => 'Renault', 'model' => 'Austral'],
            ['brand' => 'Renault', 'model' => 'Avantime'],
            ['brand' => 'Renault', 'model' => 'Captur'],
            ['brand' => 'Renault', 'model' => 'Clio'],
            ['brand' => 'Renault', 'model' => 'Espace'],
            ['brand' => 'Renault', 'model' => 'Fluence'],
            ['brand' => 'Renault', 'model' => 'Kadjar'],
            ['brand' => 'Renault', 'model' => 'Kangoo'],
            ['brand' => 'Renault', 'model' => 'Koleos'],
            ['brand' => 'Renault', 'model' => 'Laguna'],
            ['brand' => 'Renault', 'model' => 'Master'],
            ['brand' => 'Renault', 'model' => 'Mégane'],
            ['brand' => 'Renault', 'model' => 'Modus'],
            ['brand' => 'Renault', 'model' => 'Safrane'],
            ['brand' => 'Renault', 'model' => 'Scénic'],
            ['brand' => 'Renault', 'model' => 'Talisman'],
            ['brand' => 'Renault', 'model' => 'Trafic'],
            ['brand' => 'Renault', 'model' => 'Twingo'],
            ['brand' => 'Renault', 'model' => 'Twizy'],
            ['brand' => 'Renault', 'model' => 'Vel Satis'],
            ['brand' => 'Renault', 'model' => 'Wind'],
            ['brand' => 'Renault', 'model' => 'Zoe'],
            ['brand' => 'Rolls-Royce', 'model' => 'Cullinan'],
            ['brand' => 'Rolls-Royce', 'model' => 'Dawn'],
            ['brand' => 'Rolls-Royce', 'model' => 'Ghost'],
            ['brand' => 'Rolls-Royce', 'model' => 'Phantom'],
            ['brand' => 'Rolls-Royce', 'model' => 'Wraith'],
            ['brand' => 'Rover', 'model' => '100-serie'],
            ['brand' => 'Rover', 'model' => '200-serie'],
            ['brand' => 'Rover', 'model' => '25'],
            ['brand' => 'Rover', 'model' => '400-serie'],
            ['brand' => 'Rover', 'model' => '45'],
            ['brand' => 'Rover', 'model' => '600-serie'],
            ['brand' => 'Rover', 'model' => '75'],
            ['brand' => 'Rover', 'model' => '800-serie'],
            ['brand' => 'Rover', 'model' => 'Mini'],
            ['brand' => 'Rover', 'model' => 'Tourer'],
            ['brand' => 'Saab', 'model' => '9-3'],
            ['brand' => 'Saab', 'model' => '9-4X'],
            ['brand' => 'Saab', 'model' => '9-5'],
            ['brand' => 'Saab', 'model' => '9-7X'],
            ['brand' => 'Saab', 'model' => '900'],
            ['brand' => 'Saab', 'model' => '9000'],
            ['brand' => 'Seat', 'model' => 'Alhambra'],
            ['brand' => 'Seat', 'model' => 'Altea'],
            ['brand' => 'Seat', 'model' => 'Arona'],
            ['brand' => 'Seat', 'model' => 'Arosa'],
            ['brand' => 'Seat', 'model' => 'Ateca'],
            ['brand' => 'Seat', 'model' => 'Cordoba'],
            ['brand' => 'Seat', 'model' => 'Exeo'],
            ['brand' => 'Seat', 'model' => 'Ibiza'],
            ['brand' => 'Seat', 'model' => 'Leon'],
            ['brand' => 'Seat', 'model' => 'Marbella'],
            ['brand' => 'Seat', 'model' => 'Mii'],
            ['brand' => 'Seat', 'model' => 'Tarraco'],
            ['brand' => 'Seat', 'model' => 'Toledo'],
            ['brand' => 'Seres', 'model' => '3'],
            ['brand' => 'Skoda', 'model' => 'Citigo'],
            ['brand' => 'Skoda', 'model' => 'Enyaq'],
            ['brand' => 'Skoda', 'model' => 'Fabia'],
            ['brand' => 'Skoda', 'model' => 'Favorit'],
            ['brand' => 'Skoda', 'model' => 'Felicia'],
            ['brand' => 'Skoda', 'model' => 'Kamiq'],
            ['brand' => 'Skoda', 'model' => 'Karoq'],
            ['brand' => 'Skoda', 'model' => 'Kodiaq'],
            ['brand' => 'Skoda', 'model' => 'Octavia'],
            ['brand' => 'Skoda', 'model' => 'Rapid'],
            ['brand' => 'Skoda', 'model' => 'Roomster'],
            ['brand' => 'Skoda', 'model' => 'Scala'],
            ['brand' => 'Skoda', 'model' => 'Superb'],
            ['brand' => 'Skoda', 'model' => 'Yeti'],
            ['brand' => 'Smart', 'model' => 'City-Coupé'],
            ['brand' => 'Smart', 'model' => 'Crossblade'],
            ['brand' => 'Smart', 'model' => 'Forfour'],
            ['brand' => 'Smart', 'model' => 'Fortwo'],
            ['brand' => 'Smart', 'model' => 'Roadster'],
            ['brand' => 'SsangYong', 'model' => 'Actyon'],
            ['brand' => 'SsangYong', 'model' => 'Korando'],
            ['brand' => 'SsangYong', 'model' => 'Kyron'],
            ['brand' => 'SsangYong', 'model' => 'Musso'],
            ['brand' => 'SsangYong', 'model' => 'Rexton'],
            ['brand' => 'SsangYong', 'model' => 'Rodius'],
            ['brand' => 'SsangYong', 'model' => 'Tivoli'],
            ['brand' => 'SsangYong', 'model' => 'XLV'],
            ['brand' => 'Subaru', 'model' => 'BRZ'],
            ['brand' => 'Subaru', 'model' => 'Forester'],
            ['brand' => 'Subaru', 'model' => 'Impreza'],
            ['brand' => 'Subaru', 'model' => 'Justy'],
            ['brand' => 'Subaru', 'model' => 'Legacy'],
            ['brand' => 'Subaru', 'model' => 'Levorg'],
            ['brand' => 'Subaru', 'model' => 'Outback'],
            ['brand' => 'Subaru', 'model' => 'Solterra'],
            ['brand' => 'Subaru', 'model' => 'SVX'],
            ['brand' => 'Subaru', 'model' => 'Trezia'],
            ['brand' => 'Subaru', 'model' => 'Tribeca'],
            ['brand' => 'Subaru', 'model' => 'Vivio'],
            ['brand' => 'Subaru', 'model' => 'WRX'],
            ['brand' => 'Subaru', 'model' => 'XV'],
            ['brand' => 'Suzuki', 'model' => 'Across'],
            ['brand' => 'Suzuki', 'model' => 'Alto'],
            ['brand' => 'Suzuki', 'model' => 'Baleno'],
            ['brand' => 'Suzuki', 'model' => 'Celerio'],
            ['brand' => 'Suzuki', 'model' => 'Grand Vitara'],
            ['brand' => 'Suzuki', 'model' => 'Ignis'],
            ['brand' => 'Suzuki', 'model' => 'Jimny'],
            ['brand' => 'Suzuki', 'model' => 'Kizashi'],
            ['brand' => 'Suzuki', 'model' => 'Liana'],
            ['brand' => 'Suzuki', 'model' => 'S-Cross'],
            ['brand' => 'Suzuki', 'model' => 'Splash'],
            ['brand' => 'Suzuki', 'model' => 'Swace'],
            ['brand' => 'Suzuki', 'model' => 'Swift'],
            ['brand' => 'Suzuki', 'model' => 'SX4'],
            ['brand' => 'Suzuki', 'model' => 'Vitara'],
            ['brand' => 'Suzuki', 'model' => 'Wagon R+'],
            ['brand' => 'Tesla', 'model' => 'Model 3'],
            ['brand' => 'Tesla', 'model' => 'Model S'],
            ['brand' => 'Tesla', 'model' => 'Model X'],
            ['brand' => 'Tesla', 'model' => 'Model Y'],
            ['brand' => 'Tesla', 'model' => 'Roadster'],
            ['brand' => 'Toyota', 'model' => 'Auris'],
            ['brand' => 'Toyota', 'model' => 'Avensis'],
            ['brand' => 'Toyota', 'model' => 'Avensis Verso'],
            ['brand' => 'Toyota', 'model' => 'Aygo'],
            ['brand' => 'Toyota', 'model' => 'bZ4X'],
            ['brand' => 'Toyota', 'model' => 'C-HR'],
            ['brand' => 'Toyota', 'model' => 'Camry'],
            ['brand' => 'Toyota', 'model' => 'Carina'],
            ['brand' => 'Toyota', 'model' => 'Celica'],
            ['brand' => 'Toyota', 'model' => 'Corolla'],
            ['brand' => 'Toyota', 'model' => 'Corolla Cross'],
            ['brand' => 'Toyota', 'model' => 'Corolla Verso'],
            ['brand' => 'Toyota', 'model' => 'Funcruiser'],
            ['brand' => 'Toyota', 'model' => 'GR86'],
            ['brand' => 'Toyota', 'model' => 'GT86'],
            ['brand' => 'Toyota', 'model' => 'Highlander'],
            ['brand' => 'Toyota', 'model' => 'Hilux'],
            ['brand' => 'Toyota', 'model' => 'iQ'],
            ['brand' => 'Toyota', 'model' => 'Land Cruiser'],
            ['brand' => 'Toyota', 'model' => 'Land Cruiser V8'],
            ['brand' => 'Toyota', 'model' => 'Mirai'],
            ['brand' => 'Toyota', 'model' => 'MR2'],
            ['brand' => 'Toyota', 'model' => 'Previa'],
            ['brand' => 'Toyota', 'model' => 'Prius'],
            ['brand' => 'Toyota', 'model' => 'Prius+'],
            ['brand' => 'Toyota', 'model' => 'Proace City'],
            ['brand' => 'Toyota', 'model' => 'RAV4'],
            ['brand' => 'Toyota', 'model' => 'Starlet'],
            ['brand' => 'Toyota', 'model' => 'Supra'],
            ['brand' => 'Toyota', 'model' => 'Urban Cruiser'],
            ['brand' => 'Toyota', 'model' => 'Verso'],
            ['brand' => 'Toyota', 'model' => 'Verso-S'],
            ['brand' => 'Toyota', 'model' => 'Yaris'],
            ['brand' => 'Toyota', 'model' => 'Yaris Cross'],
            ['brand' => 'Toyota', 'model' => 'Yaris Verso'],
            ['brand' => 'Vinfast', 'model' => 'VF8'],
            ['brand' => 'Vinfast', 'model' => 'VF9'],
            ['brand' => 'Volkswagen', 'model' => 'Amarok'],
            ['brand' => 'Volkswagen', 'model' => 'Arteon'],
            ['brand' => 'Volkswagen', 'model' => 'Beetle'],
            ['brand' => 'Volkswagen', 'model' => 'Bora'],
            ['brand' => 'Volkswagen', 'model' => 'Caddy'],
            ['brand' => 'Volkswagen', 'model' => 'CC'],
            ['brand' => 'Volkswagen', 'model' => 'Corrado'],
            ['brand' => 'Volkswagen', 'model' => 'Crafter'],
            ['brand' => 'Volkswagen', 'model' => 'Eos'],
            ['brand' => 'Volkswagen', 'model' => 'Fox'],
            ['brand' => 'Volkswagen', 'model' => 'Golf'],
            ['brand' => 'Volkswagen', 'model' => 'Golf Plus'],
            ['brand' => 'Volkswagen', 'model' => 'Golf Sportsvan'],
            ['brand' => 'Volkswagen', 'model' => 'ID Buzz'],
            ['brand' => 'Volkswagen', 'model' => 'ID3'],
            ['brand' => 'Volkswagen', 'model' => 'ID4'],
            ['brand' => 'Volkswagen', 'model' => 'ID5'],
            ['brand' => 'Volkswagen', 'model' => 'ID6'],
            ['brand' => 'Volkswagen', 'model' => 'Jetta'],
            ['brand' => 'Volkswagen', 'model' => 'Lupo'],
            ['brand' => 'Volkswagen', 'model' => 'Multivan'],
            ['brand' => 'Volkswagen', 'model' => 'New Beetle'],
            ['brand' => 'Volkswagen', 'model' => 'Passat'],
            ['brand' => 'Volkswagen', 'model' => 'Phaeton'],
            ['brand' => 'Volkswagen', 'model' => 'Polo'],
            ['brand' => 'Volkswagen', 'model' => 'Scirocco'],
            ['brand' => 'Volkswagen', 'model' => 'Sharan'],
            ['brand' => 'Volkswagen', 'model' => 'T-Cross'],
            ['brand' => 'Volkswagen', 'model' => 'T-Roc'],
            ['brand' => 'Volkswagen', 'model' => 'Taigo'],
            ['brand' => 'Volkswagen', 'model' => 'Tiguan'],
            ['brand' => 'Volkswagen', 'model' => 'Touareg'],
            ['brand' => 'Volkswagen', 'model' => 'Touran'],
            ['brand' => 'Volkswagen', 'model' => 'Transporter'],
            ['brand' => 'Volkswagen', 'model' => 'Up'],
            ['brand' => 'Volkswagen', 'model' => 'Vento'],
            ['brand' => 'Volkswagen', 'model' => 'XL1'],
            ['brand' => 'Volvo', 'model' => '240'],
            ['brand' => 'Volvo', 'model' => '340'],
            ['brand' => 'Volvo', 'model' => '360'],
            ['brand' => 'Volvo', 'model' => '440'],
            ['brand' => 'Volvo', 'model' => '460'],
            ['brand' => 'Volvo', 'model' => '480'],
            ['brand' => 'Volvo', 'model' => '740'],
            ['brand' => 'Volvo', 'model' => '760'],
            ['brand' => 'Volvo', 'model' => '780'],
            ['brand' => 'Volvo', 'model' => '850'],
            ['brand' => 'Volvo', 'model' => '940'],
            ['brand' => 'Volvo', 'model' => '960'],
            ['brand' => 'Volvo', 'model' => 'C30'],
            ['brand' => 'Volvo', 'model' => 'C40'],
            ['brand' => 'Volvo', 'model' => 'C70'],
            ['brand' => 'Volvo', 'model' => 'EX90'],
            ['brand' => 'Volvo', 'model' => 'S40'],
            ['brand' => 'Volvo', 'model' => 'S60'],
            ['brand' => 'Volvo', 'model' => 'S70'],
            ['brand' => 'Volvo', 'model' => 'S80'],
            ['brand' => 'Volvo', 'model' => 'S90'],
            ['brand' => 'Volvo', 'model' => 'V40'],
            ['brand' => 'Volvo', 'model' => 'V50'],
            ['brand' => 'Volvo', 'model' => 'V60'],
            ['brand' => 'Volvo', 'model' => 'V70'],
            ['brand' => 'Volvo', 'model' => 'V90'],
            ['brand' => 'Volvo', 'model' => 'XC40'],
            ['brand' => 'Volvo', 'model' => 'XC60'],
            ['brand' => 'Volvo', 'model' => 'XC70'],
            ['brand' => 'Volvo', 'model' => 'XC90'],
            ['brand' => 'Xpeng', 'model' => 'P5'],
            ['brand' => 'Xpeng', 'model' => 'P7'],
        ];
        return $cars[array_rand($cars, 1)];
    }


}
